name: Robot container

on: [push]

jobs:
  robot_framework_tests_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout demo-content-room
        uses: actions/checkout@v4
        with:
          path: 'tests/demo-content-room'
          repository: 'DioryMe/demo-content-room'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t robot-tests .

      - name: Run main.robot (default CMD)
        run: docker run robot-tests

      - name: Run main-http.robot
        run: docker run robot-tests robot tests/main-http.robot
