name: Robot container

on: [push]

jobs:
  robot_framework_tests_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Image
        run: |
          docker build -t robot-tests .
          docker run robot-tests
