# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test (yarn build & test)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: yarn

      # NOTE: This is run before yarn build on purpose (to prevent test files in dist/ folder)
      - run: yarn global add bun
      - run: yarn test
        continue-on-error: true

      - run: yarn build
